/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddSingDialog: typeof import('./src/components/home/addSingDialog.vue')['default']
    AppSettingTab: typeof import('./src/components/settings/appSettingTab.vue')['default']
    BiliCredential: typeof import('./src/components/settings/biliCredential.vue')['default']
    BiliTab: typeof import('./src/components/settings/biliTab.vue')['default']
    BlankLayout: typeof import('./src/components/layout/blankLayout.vue')['default']
    DefaultLayout: typeof import('./src/components/layout/defaultLayout.vue')['default']
    DyTab: typeof import('./src/components/settings/dyTab.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElTour: typeof import('element-plus/es')['ElTour']
    ElTourStep: typeof import('element-plus/es')['ElTourStep']
    FansClub: typeof import('./src/components/common/fansClub.tsx')['default']
    FansMedal: typeof import('./src/components/common/fansMedal.tsx')['default']
    LineHeader: typeof import('./src/components/common/lineHeader.tsx')['default']
    LinkIcon: typeof import('./src/components/common/linkIcon.tsx')['default']
    ObsSetting: typeof import('./src/components/settings/obsSetting.vue')['default']
    PlatformStatus: typeof import('./src/components/home/platformStatus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vInfiniteScroll: typeof import('element-plus/es')['ElInfiniteScroll']
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}

// For TSX support
declare global {
  const AddSingDialog: typeof import('./src/components/home/addSingDialog.vue')['default']
  const AppSettingTab: typeof import('./src/components/settings/appSettingTab.vue')['default']
  const BiliCredential: typeof import('./src/components/settings/biliCredential.vue')['default']
  const BiliTab: typeof import('./src/components/settings/biliTab.vue')['default']
  const BlankLayout: typeof import('./src/components/layout/blankLayout.vue')['default']
  const DefaultLayout: typeof import('./src/components/layout/defaultLayout.vue')['default']
  const DyTab: typeof import('./src/components/settings/dyTab.vue')['default']
  const ElAside: typeof import('element-plus/es')['ElAside']
  const ElBacktop: typeof import('element-plus/es')['ElBacktop']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
  const ElContainer: typeof import('element-plus/es')['ElContainer']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElIcon: typeof import('element-plus/es')['ElIcon']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElMain: typeof import('element-plus/es')['ElMain']
  const ElMenu: typeof import('element-plus/es')['ElMenu']
  const ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
  const ElOption: typeof import('element-plus/es')['ElOption']
  const ElSelect: typeof import('element-plus/es')['ElSelect']
  const ElSwitch: typeof import('element-plus/es')['ElSwitch']
  const ElText: typeof import('element-plus/es')['ElText']
  const ElTooltip: typeof import('element-plus/es')['ElTooltip']
  const ElTour: typeof import('element-plus/es')['ElTour']
  const ElTourStep: typeof import('element-plus/es')['ElTourStep']
  const FansClub: typeof import('./src/components/common/fansClub.tsx')['default']
  const FansMedal: typeof import('./src/components/common/fansMedal.tsx')['default']
  const LineHeader: typeof import('./src/components/common/lineHeader.tsx')['default']
  const LinkIcon: typeof import('./src/components/common/linkIcon.tsx')['default']
  const ObsSetting: typeof import('./src/components/settings/obsSetting.vue')['default']
  const PlatformStatus: typeof import('./src/components/home/platformStatus.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}