"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
import sys
from scripts.setup_darwin import build_darwin
from scripts.setup_win32 import build_win32
from scripts.setup_linux import build_linux


packages = ["webview", "uvloop", "uvicorn", "tortoise", "pydantic", "objc", "anyio"]
DATA_FILES = [
    ("wwwroot", ["wwwroot/favicon.ico", "wwwroot/index.html"]),
    (
        "wwwroot/assets",
        [
            "wwwroot/assets/setting-B2XOa-Qr.js",
            "wwwroot/assets/biliTab-BQ4u2h9e.css",
            "wwwroot/assets/dyTab-04-0txVw.css",
            "wwwroot/assets/index-CH9Pwysp.js",
            "wwwroot/assets/el-input-KSoFryXZ.js",
            "wwwroot/assets/dyTab-Bt3f2w04.js",
            "wwwroot/assets/biliTab-z95ZRE3i.js",
            "wwwroot/assets/Home-g6uFqyDJ.css",
            "wwwroot/assets/index-Csm1QA7T.js",
            "wwwroot/assets/setting-nXOW1DjU.css",
            "wwwroot/assets/Home-BOrZ57wK.js",
            "wwwroot/assets/el-input-EA16acr3.css",
            "wwwroot/assets/chat-CRjwM5Pl.js",
            "wwwroot/assets/chat-DAoi8i3j.css",
            "wwwroot/assets/index-DEHPPyHn.css",
            "wwwroot/assets/request-C8K2WuSa.js",
            "wwwroot/assets/request-fwQOLwdi.css"
        ],
    ),
    (
        "wwwroot/assets/images",
        [
            "wwwroot/assets/images/douyin.png",
            "wwwroot/assets/images/bilibili.png",
            "wwwroot/assets/images/logo.png"
        ],
    ),
]

if sys.platform == "darwin":
    build_darwin(packages, DATA_FILES)
elif sys.platform == "win32":
    build_win32(packages, DATA_FILES)
else:
    build_linux(packages, DATA_FILES)
