"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup
from src.utils import get_version


def build_linux(packages, data_files):
    """
    Build the Linux executable using py2app
    """

    setup_options = {
        "iconfile": "logo.icns",
        "argv_emulation": False,
        "packages": packages
    }

    setup(
        scripts=["main.py"],
        name="VSingerBoard",
        version=get_version(),
        description="Multi-platform Singerboard",
        url="https://github.com/zangxx66",
        setup_requires=["py2app"],
        data_files=data_files,
        options={"py2app": setup_options}
    )
