"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup
from src.utils import get_version


def build_darwin(packages, data_files):
    """
    Build py2app for Darwin platform
    """
    app_options = {
        "iconfile": "logo.icns",
        "argv_emulation": False,
        "packages": packages,
        "plist": {
            "CFBundleName": "VSingerBoard",
            "CFBundleDisplayName": "点歌板",
            "CFBundleVersion": get_version(),
            "CFBundleIdentifier": "com.ricardo.vsingerboard",
            "DTSDKBuild": "24G90",
            "DTSDKName": "macOS 15.0",
            "LSMinimumSystemVersion": "15.0",
            "NSHumanReadableCopyright": "Copyright  2025 Ricardo All rights reserved.",
            "NSAppTransportSecurity": {
                "NSAllowsArbitraryLoads": True,
                "NSAllowsLocalNetworking": True,
                "NSExceptionDomains": {
                    "127.0.0.1": {
                        "NSIncludesSubdomains": False,
                        "NSTemporaryExceptionAllowsInsecureHTTPLoads": True,
                        "NSTemporaryExceptionAllowsInsecureHTTPSLoads": False,
                        "NSTemporaryExceptionMinimumTLSVersion": "1.0",
                        "NSTemporaryExceptionRequiresForwardSecrecy": False
                    }
                }
            },
            "NSMainNibFile": "MainMenu",
            "NSSupportsAutomaticGraphicsSwitching": True,
            "NSBluetoothAlwaysUsageDescription": "This app needs access to Bluetooth",
            "NSBluetoothPeripheralUsageDescription": "This app needs access to Bluetooth",
            "NSCameraUsageDescription": "This app needs access to Camera",
            "NSHighResolutionCapable": True,
            "NSDocumentsFolderUsageDescription": "This app needs access to Documents",
            "NSDownloadsFolderUsageDescription": "This app needs access to Downloads",
            "NSLibraryFolderUsageDescription": "This app needs access to Library"
        }
    }
    setup(
        app=["main.py"],
        name="VSingerBoard",
        version=get_version(),
        description="Multi-platform Singerboard",
        url="https://github.com/zangxx66",
        setup_requires=["py2app"],
        data_files=data_files,
        options={"py2app": app_options}
    )
