"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""
from setuptools import setup
from src.utils import get_version


def build_win32(packages, data_files):
    """
    Build the Windows executable using py2app
    """

    options = {
        "iconfile": "logo.icns",
        "argv_emulation": False,
        "packages": packages
    }

    setup(
        app=["main.py"],
        name="VSingerBoard",
        version=get_version(),
        description="Multi-platform Singerboard",
        url="https://github.com/zangxx66",
        setup_requires=["py2exe"],
        data_files=data_files,
        options={"py2exe": options}
    )
